webdav-domain {
  org.exoplatform.web.login.FilterDisabledLoginModule required
    portalContainerName=portal
    realmName=webdav-domain;
  org.exoplatform.documents.webdav.security.WebDavDigestLoginModule required
    portalContainerName=portal
    realmName=webdav-domain;
};
