webdav-domain {
  org.exoplatform.web.login.FilterDisabledLoginModule required
    portalContainerName=portal
    realmName=webdav-domain;
  io.meeds.web.security.authenticator.DigestLoginModule required
    portalContainerName=portal
    realmName=webdav-domain;
};
