#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
  {
    "source": "/documents-webapp/src/main/resources/locale/commons/Commons_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest": "add__ons/documents/Commons.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },{
    "source" : "/documents-webapp/src/main/resources/locale/portlet/Documents_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/Documents.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portal/webui_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/Webui.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/notification/DocumentsNotification_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/DocumentsNotification.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/Analytics_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/Analytics.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/LayoutEditor_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/LayoutEditor.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/ContentLink_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/ContentLink.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/OfflineApplication_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/OfflineApplication.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/social/UserSettings_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/UserSettings.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/Portlets_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/Portlets.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/navigation/portal/global_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/global.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/TrashManagement_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/TrashManagement.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/attachments_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/attachments.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/documents-webapp/src/main/resources/locale/portlet/ckeditor_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/documents/ckeditor.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
]
