name: PR lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@master
      with:
        title-regex: '^(MAINT-|TASK-|EXO-)?\d+:.*'
        title-regex-flags: 'gim'
        error-message: 'You need to specify the task ID for this PR'